# Getting Started {#get-started}

<!-- Maybe a more gradual introduction ? -->

Bookdown is an open-source R package that helps write books and articles. We will be building our bookdown-based workshop websites using this, specifically the gitbook template. (This is just the name of the specific template style, you will be working in a workshop template that CBW has prepared for you!)

If you're ready to start making a workshop website in bookdown, let's setup your device (PC, laptop)!

First, let's explain installations.

## Installation

Since bookdown is an R package, you will need R. Plus, our ideal IDE (integrated development environment i.e. the platform we will be working in) is RStudio.

<!-- [Maybe we should have more installation instructions - a video?] -->

1.  **Download and install R** <a href="https://cran.rstudio.com/" target="_blank">here</a>. (You need R 3.6.0+ installed for RStudio.) Follow the instructions for your operating system (Linux/macOS/Windows).
    
    :::: {.greenbox data-latex=""}
    ::: {.center data-latex=""}
    **Check if you installed properly!**
    :::
    
    *MacOS*
    
    Run the command "R" in terminal. An R Console should start and you should be able to start running R commands. <br>
    
    *Windows*
    
    ::::
    
    > Note: **We will not be using the R console**, instead, we will be using RStudio!

2.  **Download and install RStudio** <a href="https://posit.co/download/rstudio-desktop/#:~:text=AND%20INSTALL%20R-,2%3A%20Install%20RStudio,-DOWNLOAD%20RSTUDIO%20DESKTOP" target="_blank">here</a>. Scroll down to find downloads for non-macOS.

    > Note: While installing, you may be asked whether to install the 32-bit or 62-bit RStudio version. Download the version that matches your PC.

3.  **Install Git, if you don't already have it.** Git is a tool that will help us with version control when editing your workshop. Linux and macOS computers tend to have Git installed. Windows computers must install Git. However, make sure to double check if you already have Git, so that you don't have to install it again! Check if you have Git by running this command in terminal/command prompt:

    ```{bash}
    git --version
    ```

    If your output looks like "git version X.X.X ...", you already have git! Move onto step 4!

    However, if your output says "Git is not recognized" or a similar statement (such as the one provided below), you do not have Git, so you must install it as well.

    ```
    'git' is not recognized as an internal or external command,
    operable program or batch file.
    ```
    
    <a href="https://github.com/git-guides/install-git#install-git-on-mac" target="_blank">**Installing Git on macOS**</a>
    
    - When you ran `git --version`, it will have prompted you to install Git. Follow these instructions.
    
    <a href="https://github.com/git-guides/install-git#install-git-on-windows" target="_blank">**Installing Git on Windows**</a>

    - Go to the <a href="https://posit.co/download/rstudio-desktop/#:~:text=AND%20INSTALL%20R-,2%3A%20Install%20RStudio,-DOWNLOAD%20RSTUDIO%20DESKTOP" target="_blank">Git for Windows installer</a> and download Git. Then, install it with all the default settings.

    Click here for instructions on <a href="https://github.com/git-guides/install-git#install-git-on-windows" target="_blank">**installing Git on Linux**</a>.
    
    :::: {.greenbox data-latex=""}
    ::: {.center data-latex=""}
    **Double Check!**
    :::
    
    Check that your install worked! Re-run "git -\-verison" and check that you get your git version! (On Windows, this may look like "git version 2.47.1.windows.1").
    
    > Note: If you installed Git while having a Command Prompt/Windows PowerShell window open, close this window and open a new one to run "git -\-version". This acts as a refresher to Command Prompt/Windows PowerShell.
    
    ::::
    <br>

4.  **Install the bookdown R package**: Open RStudio and in the console (in the bottom left window of RStudio) run the following command: `install.packages("bookdown")`.

    -   **Download all the packages you will need!** Do this by running the following command:

        ``` r
        install.packages(c("magrittr", "stringi", "stringr", "reticulate", "tinytex","servr"))
        ```

        You may have to approve some downloads. Say "yes" and enter your password when necessary. This tells bookdown you are okay with downloading and installing these packages in their default locations.

        Finally, **run the following command**

        ``` r
        tinytex::install_tinytex()
        ```

We're ready to start working with CBW's bookdown workshop template now!

:::: {.bluebox data-latex=""}
::: {.center data-latex=""}
**Go to the next step**
:::

Now that you're done the installations, it's time to go to the next step: [creating a **new** workshop](#rc-workshop-setup), if you're a RC, or [seeing your deployed website](#check-deploy) (skip to step 4), if you're on the workshop team. The order of this documentation is provided in the sidebar on the left. You can also click the arrows below, to go to the previous or subsequent page!
::::
