# **Recurring Workshop**: Creation [RC] and Deployment

Certain aspects of the setup for workshops will be different depending on your role. Headers ending in "[RC]" are for Regional Coordinators. Headers without "[RC]" are assumed to be relevant to both RC and workshop teams.

## Recreate the Workshop

git fork

## Deploying Your Workshop Website

Deploying your (turning your files into a) website is actually the exact same as deploying for a new workshop website.

<!-- For now, we can just link to that part in the, deploying a new workshop website, page. Alternatively, we can just copy paste it here and make some edits, or combine the 2 pages. -->

## Making Updates

Follow the [Command Line, SSH Connection & Git Clone](#git-instruct) and [So What Do These Files Mean?](#file-explanation) pages to figure out how to start editing your workshop. However, since it is a recurring workshop, you may not need to edit much.

If you are only editing the name, date and other small details <!-- there is a word for this I can't think of right now -->, consider only editing the _output.yml and index.Rmd file. 

See [Formatting Your Content - Markdown](#formatting) for an explanation in how to edit the actual files, and more on Markdown syntax!
