# Brain Dump / FAQ


## Danger Zones

- renaming your file with this project, doesn't change the .Rprog file!


- GIT TIPS PAGE ???
- BEST PRACTICES PAGE

- MAKE SURE TO EXPLAIN WHAT HAPPENS WHEN MERGE CONFLICTS APPEAR

Ex. Forgot to pull before editing?
- Your git window will say (at the top of the window) your branch is ahead of the main branch
- You will probably have to deal with a merge conflict
- [this is pretty in-depth]

- update favicon.ico image in template with one with higher quality


## Potential Errors & Bugs

- If you get a bug where your website builds into a website that looks like it is made using very simple html, you may have to change your permissions. If you see **"Permission denied"** in your warning messages, trying running this command ```chmod -R u+w docs``` in terminal, in the folder containing your docs folder [CLARIFY ?]

- **"Could not produce X output"** - by default, bookdown builds all possible formats: gitbook, pdf, epub versions. We only need the gitbook, so if you're having issues, change your build settings to only creating the gitbook [CLARIFY + INCLUDE IMAGES]

- A very common bug is **"missing X package"**, just install it using this command in your console (the bottom left window in RStudio) ```install.packages("missing package name, include these surrouding quotations") ```

## Ease of Use

### Wrapping Your Code
Sometimes, RStudio defaults so that there is no text wrapping when viewing your files. If you notice that you have to scroll horizontally to see the long lines in your files, turn on "Soft-Wrap Long Lines".
1. In your upper left corner of your RStudio Window, you will see options "File", "Edit", "Code". (If you are in full-screen on a mac, you will have to bring your cursor to the upper left corner before seeing these options). Click "Code".
2. Go to the 5th option "Soft-Wrap Long Lines" and select it.

## FAQs
